# fly.toml file generated for wa on 2023-01-13T19:41:35+07:00

app = "wa"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[mounts]
source = "f"
destination = "/app/auth_data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
