# fly.toml file generated for hhhh on 2023-03-11T23:23:16+07:00

app = "wa"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/app/auth_data"
  source = "f"
